### ISSUE TITLE
verilator compile fails

### ISSUE THREAD

**Issue by pxs7** [OpenPOWERFoundation/a2o#16]
when use  verilator compile, the following
%Error: Command Failed /bin/verilator_bin -cc --exe --trace --Mdir obj_dir --language 1364-2001 -Wno-fatal -Wno-LITENDIAN --error-limit 1 -Iverilog/work -Iverilog/trilib_clk1x -Iverilog/trilib -Iverilog/unisims c.v tb.cpp

**Comment by openpowerwtf** [comment]
This issue was resolved around that timeframe:

https://github.com/verilator/verilator/issues/3543

**Comment by openpowerwtf** [comment]
Verilator and Iverilog compile/simulate OK.
